version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
  my-db:
